import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const exportToPDF = ({
  title = "Report",
  subtitle = "",
  columns = [],
  rows = [],
  fileName = "Report",
  orientation,
  societyName = "Society",
  meta = {},
}) => {
  // Auto landscape if more than 4 columns or explicitly requested
  const isLandscape = orientation ? orientation === "landscape" : columns.length >= 5;
  const doc = new jsPDF({
    orientation: isLandscape ? "landscape" : "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 14;
  let currentY = 16;

  const generatedBy = meta.generatedBy || "Committee Member";
  const roleLabel = meta.roleLabel || "Member";
  const exportedAt =
    meta.exportedAt ||
    new Date().toLocaleString("en-IN", {
      dateStyle: "medium",
      timeStyle: "short",
    });

  // Society header bar (mirrors mobile buildTableHTML)
  doc.setFillColor(124, 58, 237); // #7C3AED
  doc.setDrawColor(124, 58, 237);
  doc.roundedRect(marginLeft, currentY - 10, pageWidth - marginLeft * 2, 18, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(societyName, marginLeft + 4, currentY - 2);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(title, marginLeft + 4, currentY + 3);
  currentY += 18;

  // Meta rows (Generated By / Role / Timestamp)
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139); // slate-500
  const metaLine = `Generated By: ${generatedBy}  ·  Role: ${roleLabel}  ·  Timestamp: ${exportedAt}`;
  doc.text(metaLine, marginLeft, currentY + 4);
  currentY += 9;

  // Subtitle (records count)
  if (subtitle) {
    doc.setFontSize(9.5);
    doc.setTextColor(100, 116, 139);
    doc.text(subtitle, marginLeft, currentY);
    currentY += 4;
  }

  // Divider line
  currentY += 2;
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setLineWidth(0.4);
  doc.line(marginLeft, currentY, pageWidth - marginLeft, currentY);

  // Table (purple header, alternating rows — mirrors mobile)
  autoTable(doc, {
    startY: currentY + 4,
    margin: { left: marginLeft, right: marginLeft },
    head: [columns],
    body: rows,
    theme: "grid",
    styles: {
      fontSize: 8.5,
      cellPadding: { top: 3, right: 3, bottom: 3, left: 3 },
      textColor: [30, 41, 59],
      lineColor: [226, 232, 240],
      lineWidth: 0.2,
      overflow: "linebreak",
      font: "helvetica",
    },
    headStyles: {
      fillColor: [124, 58, 237], // #7C3AED
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8.5,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252], // slate-50
    },
    didDrawPage: (data) => {
      // Footer page number
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(148, 163, 184); // slate-400
      const pageStr = `Page ${doc.internal.getNumberOfPages()}`;
      doc.text(pageStr, pageWidth - marginLeft - doc.getTextWidth(pageStr), pageHeight - 8);
      doc.text("Generated by Society Management App", marginLeft, pageHeight - 8);
    },
  });

  doc.save(`${fileName}.pdf`);
};