import * as XLSX from "xlsx";

/* CSV export with metadata header rows, mirroring the mobile exportCSVFile format. */
const csvCell = (value) => {
  const str = String(value ?? "");
  return str.includes(",") || str.includes('"') || str.includes("\n")
    ? `"${str.replace(/"/g, '""')}"`
    : str;
};

export const exportToCSV = ({
  data,
  fileName = "Report",
  meta = {},
}) => {
  const headers = data.length ? Object.keys(data[0]) : [];
  const exportedAt =
    meta.exportedAt ||
    new Date().toLocaleString("en-IN", {
      dateStyle: "medium",
      timeStyle: "short",
    });

  const rows = [
    `# Society: ${csvCell(meta.societyName || "Society")}`,
    `# Role: ${csvCell(meta.roleLabel || "Member")}`,
    `# Generated By: ${csvCell(meta.generatedBy || "Committee Member")}`,
    `# Exported At: ${csvCell(exportedAt)}`,
    "",
    headers.map(csvCell).join(","),
    ...data.map((row) => headers.map((h) => csvCell(row[h])).join(",")),
  ];

  // UTF-8 BOM so Excel/Google Sheets render non-ASCII correctly
  const blob = new Blob(["\uFEFF" + rows.join("\n")], {
    type: "text/csv;charset=utf-8;",
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${fileName}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const exportToExcel = ({
  data,
  fileName = "Report",
  sheetName = "Sheet1",
}) => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  XLSX.writeFile(workbook, `${fileName}.xlsx`);
};